language: python
python:
- '2.7'
branches:
  except:
    - experimental

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

install:
  # Copy these states
  - sudo cp -r . /srv
  - sudo cp .travis/minion /etc/salt/minion
  - sudo cp .travis/!(top*).sls /srv/pillar/
  - sudo cp .travis/top.sls /srv/salt/
  - sudo cp -r .travis/travisminion /srv/pillar/
  - sudo service salt-minion restart

before_script:
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_highstate --local --retcode-passthrough

after_failure:
  - sudo cat /var/log/salt/minion
